### PR TITLE
Add option to allow MSAL token cache to fall back on unencrypted storage

### PR DESCRIPTION
**Pull request by calebkiage**
Work around for microsoftgraph/msgraph-cli#69

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
I'm curious, does the unencrypted token cache persist for only the life of the console session?

**Comment by calebkiage** [comment]
> I'm curious, does the unencrypted token cache persist for only the life of the console session?

It's stored in a file. Since we'll be using this option in docker, the token would persist for the lifetime of the container. However, should the user decide to create a volume for the directory it's stored in, the token would persist as long as the volume.

**Review by baywet — CHANGES_REQUESTED** [review]
I don't think we should offer that possibility, this is a potential for people to shoot themselves in the foot and leak credentials one way or another.
If the persistence is failing when encryption is enabled but works when disabled, it's most likely that azure identity/msal relies on a OS library on linux to do the encryption work. And that encryption lib is absent from the container and needs to be installed (lib-crypt, libssl, etc...)
I do think we should add another RUN entry to the container image definition to install the missing lib.

**Comment by calebkiage** [comment]
Hey @baywet, unfortunately, adding the required library (`libsecret`) doesn't work. I've outlined the problem in this issue https://github.com/microsoftgraph/msgraph-cli/issues/69

**Comment by MIchaelMainer** [comment]
@peombwa I know you faced this same situation in PowerShell. What did you end up doing?

**Comment by peombwa** [comment]
@calebkiage, we implemented a session object for PowerShell that holds the token cache in memory without writing the cache on disk. You'll then need to write an in-memory cache options class that extends Azure.Identity's [UnsafeTokenCacheOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.unsafetokencacheoptions?view=azure-dotnet#methods) class and overrides its `RefreshCacheAsync` and `TokenCacheUpdatedAsync` methods to read and write to the in-memory cache.

See PowerShell's implementation at https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/enhancements/MSIdentity/src/Authentication/Authentication.Core/TokenCache/InMemoryTokenCacheOptions.cs and https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/enhancements/MSIdentity/src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs#L123.

**Comment by calebkiage** [comment]
Hey @peombwa, @MIchaelMainer, in the case of the CLI, the program exits after each command so any data stored in memory will be lost by the time a user is running the next command. This is why we needed on-disk caching. I have figured out a way to run the docker image with encryption enabled, but the user `MUST` add the `ipc_lock` capability for it to work. This capability is required by the gnome-keyring.

**Pull request closed without merging**
