### PR TITLE
- removes PR trigger for ADO security

### PR DESCRIPTION
**Pull request by baywet**

### CODE REVIEW

**Comment by calebkiage** [comment]
Why is this needed?

**Comment by baywet** [comment]
@calebkiage compliance running ADO pipelines with secrets access (or connections) on PR from forks is a security liability. Since we do validation (CI) with GHA anyway I thought the easiest would be to remove the trigger all together.

**Comment by baywet** [comment]
@calebkiage GHA is the direction over the long run. We're only using ADO at this point because some compliance/publishing tasks are not available at this time for GHA. I thought the current agreement the team had landed on was : use GHA as much as we can (CI/CD/PR validation/...) except for the parts where we have a dependency on ADO (CD). Investing heavily on ADO is time consuming at best since we'll have to migrate back to GHA over time, and compliance requirements might become blocking (like this one of not being able to run ADO pipelines on forks anymore, which effectively prevents any external contribution, not ideal for an OSS product). Did I miss something while I was away?

**Review by calebkiage — CHANGES_REQUESTED** [review]
If the intention is to disable PR triggers, the code should be <sup>1</sup>:

```yaml
pr: none
```

[1] [Opting out of PR validation](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#opting-out-of-pr-validation)

**Comment by baywet** [comment]
ah thanks I forgot ADO had implicit opt-ins, fixed.

**Review by calebkiage — APPROVED** [review]

**Pull request merged**
